//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_CHAMCONG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_CHAMCONG()
        {
            this.tb_LUONG = new HashSet<tb_LUONG>();
        }
    
        public string MABCC { get; set; }
        public string MANV { get; set; }
        public Nullable<int> SONC { get; set; }
        public Nullable<int> TANGCA { get; set; }
        public Nullable<int> MUON { get; set; }
    
        public virtual tb_NHANVIEN tb_NHANVIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_LUONG> tb_LUONG { get; set; }
    }
}
